### ISSUE TITLE
Hide tabs or open tab when block is closed

### ISSUE THREAD

**Issue by tobimori** [junohamburg/kirby-block-preview-fields#1]
## Current behavior
When a block is closed via the chevron, tabs are persisted and clicking them does nothing except changing the selected state.

## Expected/Suggested behaviour
a. Tabs should not be visible when the block is closed **or**
b. Clicking a tab should open the block again, with the correct tab selected. The "selected tab" state should be disabled when the accordion is closed.

**Comment by SebastianEberlein-JUNO** [comment]
You’re right, the tabs should be hidden if the block is collapsed, see latest release!
