### ISSUE TITLE
Custom block label not working with unescaped HTML

### ISSUE THREAD

**Issue by lassereinboeng** [junohamburg/kirby-block-preview-fields#2]
Hi there!
I just opened an [issue on the Kirby repository](https://github.com/getkirby/kirby/issues/5346) and it might be relevant for this plugin also (I stumbled across this behavior when the kirby-block-preview-fields plugin was enabled and it shows the same behavior).

In my project I defined a custom block type which includes a headline field of type Writer (configured with the inline option).
The content of that headline field should be the label of the block in the preview. When using `label: '{{ headline }}'` I get the correct field content as my block preview label. So far, so good, but special characters in the field like "&" will be rendered as "&amp;amp;". So I tried `label: '{< headline >}'` as it is explained [here](https://getkirby.com/docs/guide/blueprints/query-language#querying-information-to-display__escaping-html). Then, the label does not show up anymore.

**To reproduce**
- Create a custom block type
- Add a field of type Writer (maybe it must have the inline option also)
- Add label: '{< headline >}' to the custom block's blueprint
- Add content with special chars (e.g. "&") to the custom block and save

Best regards,
Lasse

**Comment by SebastianEberlein-JUNO** [comment]
Thanks for the info! I re-used some code from the `BlockTitle.vue` component, for example the `label` property (see [link](https://github.com/getkirby/kirby/blob/main/panel/src/components/Forms/Blocks/BlockTitle.vue#L27)). So if the Kirby teams updates their Vue component, I will add these changes to our plugin.
