### ISSUE TITLE
k4 compatibility: needs css adjustment

### ISSUE THREAD

**Issue by bnomei** [junohamburg/kirby-block-preview-fields#4]
![CleanShot 2023-11-15 at 16 48 27](https://github.com/junohamburg/kirby-block-preview-fields/assets/3265642/0fdbf914-075e-4b93-8f4a-6c9e0ae0392b)

**Comment by SebastianEberlein-JUNO** [comment]
I’m not sure if we will release a Kirby 4 version, because Kirby 4 already has a fields preview ([docs](https://getkirby.com/releases/4.0/block-field-improvements#field-preview)).

Do you use our plugin in Kirby 4 because of the arrows that indicate if the block is collapsed?
